<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = [
            [
                'name' => 'University of Caloocan City',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-8361-0000',
                'email' => 'info@ucc.edu.ph',
                'website' => 'https://www.ucc.edu.ph',
                'classification' => 'LOCAL UNIVERSITY/COLLEGE (LUC)',
                'address' => 'Biglang Awa St, Caloocan City',
                'city' => 'Caloocan City',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City Science High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-8361-1000',
                'email' => 'info@ccshs.edu.ph',
                'website' => 'https://www.ccshs.edu.ph',
                'classification' => 'LOCAL UNIVERSITY/COLLEGE (LUC)',
                'address' => '10th Avenue, Caloocan City',
                'city' => 'Caloocan City',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'St. Gabriel Academy',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-8361-2000',
                'email' => 'info@stgabriel.edu.ph',
                'website' => 'https://www.stgabriel.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Congressional Road Extension, Caloocan City',
                'city' => 'Caloocan City',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City Business High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-8361-3000',
                'email' => 'info@ccbhs.edu.ph',
                'website' => 'https://www.ccbhs.edu.ph',
                'classification' => 'LOCAL UNIVERSITY/COLLEGE (LUC)',
                'address' => 'Rizal Avenue Extension, Caloocan City',
                'city' => 'Caloocan City',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan National Science and Technology High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-8361-4000',
                'email' => 'info@cnsths.edu.ph',
                'website' => 'https://www.cnsths.edu.ph',
                'classification' => 'LOCAL UNIVERSITY/COLLEGE (LUC)',
                'address' => 'Congressional Road Extension, Barangay 173, Caloocan City',
                'city' => 'Caloocan City',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Far Eastern University',
                'campus' => 'Nicanor Reyes Street',
                'contact_number' => '+63-2-8849-4000',
                'email' => 'info@feu.edu.ph',
                'website' => 'https://www.feu.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Nicanor Reyes Street, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1015',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Mapúa University',
                'campus' => 'Intramuros',
                'contact_number' => '+63-2-8247-5000',
                'email' => 'info@mapua.edu.ph',
                'website' => 'https://www.mapua.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Muralla Street, Intramuros',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1002',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Adamson University',
                'campus' => 'San Marcelino',
                'contact_number' => '+63-2-8524-2011',
                'email' => 'info@adamson.edu.ph',
                'website' => 'https://www.adamson.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '900 San Marcelino Street, Ermita',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1000',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'National University',
                'campus' => 'Sampaloc',
                'contact_number' => '+63-2-8712-0000',
                'email' => 'info@national-u.edu.ph',
                'website' => 'https://www.national-u.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '551 M.F. Jhocson Street, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1015',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of the East',
                'campus' => 'Recto',
                'contact_number' => '+63-2-8735-5471',
                'email' => 'info@ue.edu.ph',
                'website' => 'https://www.ue.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '2219 C.M. Recto Avenue, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1008',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
        ];

        foreach ($schools as $schoolData) {
            School::create($schoolData);
        }
    }
}
